
% doSave = false;
% fnm = fullfile('data', 'figs', 'summary', [fitnm '_dpAndCp.pdf']);

% nrows = 1; ncols = 3;
% figure; hold on; set(gcf, 'color', 'w');

plot.init;
% subplot(nrows,ncols,1); hold on; set(gca, 'FontSize', 16);
set(gca, 'LineWidth', 2);
xs = [cells.rf_ecc];
ys = [cells.dPrime];
mdl = fitlm(xs, ys);
h = mdl.plot;
h(1).Marker = 'o';
h(1).Color = 'k';
h(1).MarkerSize = 4.5;
h(1).MarkerFaceColor = 0.5*ones(3,1);
h(1).LineWidth = 1.5;
h(2).LineWidth = 2;
h(2).Color = [0.8 0.2 0.2];
set(gca, 'TickDir', 'out');
legend off;
xlabel('RF eccentricity');
ylabel('d''');
xlim([0 1.1]);
title('');
plot.setPrintSize(gcf, struct('width', 4, 'height', 3));

plot.init;
% subplot(nrows,ncols,2); hold on; set(gca, 'FontSize', 16);
set(gca, 'LineWidth', 2);
xs = [cells.rf_ecc];
ys = [cells.cp_YresARc];
xs = xs(ys > 0); ys = ys(ys > 0);
plot([min(xs) max(xs)], [0.5 0.5], 'k--', 'LineWidth', 2);
mdl = fitlm(xs, ys);
h = mdl.plot;
h(1).Marker = 'o';
h(1).Color = 'k';
h(1).MarkerSize = 4.5;
h(1).MarkerFaceColor = 0.5*ones(3,1);
h(1).LineWidth = 1.5;
h(2).LineWidth = 3;
h(2).Color = [0.8 0.2 0.2];
set(gca, 'TickDir', 'out');
legend off;
xlabel('RF eccentricity');
ylabel('CP');
xlim([0 1.1]);
% ylim([0.4 0.7]);
title('');
plot.setPrintSize(gcf, struct('width', 4, 'height', 3));

plot.init;
% subplot(nrows,ncols,3); hold on; set(gca, 'FontSize', 16);
set(gca, 'LineWidth', 2);
xs = [pairs.rfCorr];
ys = [pairs.noiseCorrAR];
plot([min(xs) max(xs)], [0 0], 'k--', 'LineWidth', 2);
mdl = fitlm(xs, ys);
h = mdl.plot;
h(1).Marker = 'o';
h(1).Color = 'k';
h(1).MarkerSize = 4.5;
h(1).MarkerFaceColor = 0.5*ones(3,1);
h(1).LineWidth = 1.5;
h(2).LineWidth = 3;
h(2).Color = [0.8 0.2 0.2];
set(gca, 'TickDir', 'out');
legend off;
xlabel('RF correlation');
ylabel('Noise correlation');
title('');
plot.setPrintSize(gcf, struct('width', 4, 'height', 3));
